### ISSUE TITLE
Timezone information is dropped when converting internally to UTC

### ISSUE THREAD

**Issue by moccacup** [ics-py/ics-py#188] opened 2019-08-01 11:59 UTC
When opening a calendarfile (*.ics), the timezone will be replaced by utc.

This causes wrong times for recurrent events. For example you use a recurring event in Europe, every month from 10:00 to 11:00 (timezone europe/berlin). It is read resp. converted correctly for now (summer) in utc (8:00 to 9:00 utc).

 But in the wintermonths the event will be at a wrong time. (8:00-9:00 utc is the 9:00-10:00 (timezone europe/berlin).

a complete examplefile:
```python
import ics

ics_orig = """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV 3.2.2//EN
X-WR-CALNAME:test
X-APPLE-CALENDAR-COLOR:#FF9500
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:MESZ
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:MEZ
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20190801T112629Z
UID:DD5E3484-E37A-4A5B-AA5D-31B8394DBF7B
RRULE:FREQ=MONTHLY;INTERVAL=1
DTEND;TZID=Europe/Berlin:20190701T110000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:every month 10:00 to 11:00
DTSTART;TZID=Europe/Berlin:20190701T100000
DTSTAMP:20190801T113222Z
SEQUENCE:0
END:VEVENT
END:VCALENDAR"""

cal = ics.Calendar(ics_orig)
ics_back = str(cal)
print (ics_back)

```

the resulting calendarfile points out only:

```
BEGIN:VCALENDAR
X-WR-CALNAME:test
X-APPLE-CALENDAR-COLOR:#FF9500
PRODID:-//SabreDAV//SabreDAV 3.2.2//EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20190801T112629Z
RRULE:FREQ=MONTHLY;INTERVAL=1
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SEQUENCE:0
DTSTAMP:20190801T113222Z
DTSTART:20190701T080000Z
DTEND:20190701T090000Z
SUMMARY:every month 10:00 to 11:00
TRANSP:OPAQUE
UID:DD5E3484-E37A-4A5B-AA5D-31B8394DBF7B
END:VEVENT
END:VCALENDAR
```

so the original DTSTART ist changed from
`DTSTART;TZID=Europe/Berlin:20190701T100000`
to
`DTSTART:20190701T080000Z`
which is correct only for summer time = "daylight" time
but is different for "Standard" -time = winter time

**Comment by C4ptainCrunch** [comment] 2019-08-01 12:48
Oh, i never thought of that case. Indeed, we transform everything as UTC internally for the moment.
I guess we should not do that, it's a bug indeed :/

**Comment by vai0** [comment] 2020-01-31 23:01
I'm experiencing something very similar
```
...
resolved_begin = arrow.get(begin).to(tz).format()
resolved_duration = { "hours": int(duration) }

print("resolved_begin:", resolved_begin)

evt.name = name
evt.begin = resolved_begin
evt.duration = resolved_duration
evt.description = description
evt.location = location
evt.url = url

cal.events.add(evt)
print(cal.events)
...
```
where the `begin` value is `2014-01-01 00:00:00`, and `tz` value is `US/Pacific`
this logs
```
resolved_begin: 2013-12-31 16:00:00-08:00
{<Event 'some name' begin:2013-12-31T16:00:00-08:00 end:2013-12-31T19:00:00-08:00>}
```
yet the output of the ics file looks like 
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DESCRIPTION:some description
DURATION:PT3H
LOCATION:534 4th St. San Francisco\, CA 94103
DTSTART:20140101T000000Z
SUMMARY:some name
UID:00eefb47-0ca1-44a1-93c1-ef623e61f0ba@00ee.org
END:VEVENT
PRODID:ics.py - http://git.io/lLljaA
VERSION:2.0
END:VCALENDAR
```
where `DTSTART` does not even match the actual passed in `begin` value printed from `cal.events`

Unless I'm misunderstanding here, this is a pretty major bug that sorta makes this lib unusable :disappointed:

**Comment by N-Coder** [comment] 2020-02-05 07:14
The unwanted conversion when parsing should be fixed when we drop Arrow and properly support naive/floating datetimes in PR #222. To ensure that the printed ics data is also always correct with timestamps having variable timezones being preserved, we probably need #129 first.

**Comment by N-Coder** [comment] 2020-06-21 12:34
We should now have a test case that checks this and prevents regressions:
https://github.com/C4ptainCrunch/ics.py/blob/01172505f3eebc792a6a3445a00f2ef0aed9b80d/tests/issues/gh181_188.py
This test passed with the latest version of the `timezones` branch, so this issue should be solved (it will be closed once we merge the branch):
https://github.com/C4ptainCrunch/ics.py/runs/792496212

**Comment by firasm** [comment] 2020-08-24 02:15
hello @N-Coder - just about to start using this module for some code to generate ics files for my courses this fall. Is the current recommendation still to pass in times in UTC rather than PDT etc ? Just trying to figure out whether I should write a wrapper function to convert times to UTC before using this library. Thanks!

**Comment by firasm** [comment] 2020-08-24 07:34
So I verified that indeed the dates are converted to UTC on input.

In case this helps anyone, I worked on some sample code to help me understand what's going on. 

```
from datetime import datetime
from dateutil import tz

date_format = '%Y-%m-%d %H:%M:%S' # Format the ics module expects the dates to be in
due = '2021-02-01 00:00:00'       # Sample date that needs to be converted to UTC (Currently in Canada/Pacific time zone)

# First let's convert this to a datetime object in the Canada/Pacific Time zone
due_dt = datetime.strptime(due,date_format).replace(tzinfo=tz.gettz('Canada/Pacific'))

# Then let's convert the date to UTC so ics can handle it correctly
due_dt = due_dt.astimezone(tz.tzutc())

# Now let's run the example in the documentation
from ics import Calendar, Event
c = Calendar()
e = Event()
e.name = "My cool event"
e.begin = due_dt.strftime(date_format) # Updated this to use date_format
c.events.add(e)
c.events
# [<Event 'My cool event' begin:2014-01-01 00:00:00 end:2014-01-01 00:00:01>]
with open('my.ics', 'w') as my_file:
    my_file.writelines(c)
```

**Closed** 2021-08-18 13:31 UTC
Labels: bug, rfc-compliance

**Comment by Maikeximu** [comment] 2022-02-08 08:25
For a quick resolution, I just replaced all the Z in events using replace. Hope it can help.

`#input file
calendrier = open("my.ics", "rt")
#output file to write the result to
cal = open("calendrier.ics", "wt")
#for each line in the input file
for line in calendrier:
	#read replace the string and write to output file
	cal.write(line.replace('Z', ''))
#close input and output files
calendrier.close()
cal.close()`
