### ISSUE TITLE
Timezone information of time fields is ignored

### ISSUE THREAD

**Issue by C4ptainCrunch** [ics-py/ics-py#181] opened 2019-06-26 08:59 UTC
See https://github.com/C4ptainCrunch/ics.py/pull/113#issue-170060315

> Timezone information of time fields is ignored, e.g. if COMPLETED:;TZID=Europe/Brussels:20180418T150001 is parsed, it won't store the timezone.

This also looks like a bug, it might be from all the arrow mess that i have to clean. I'll look into it (but feel free to open an issue with code example if you want to)

Might be that #68 is not yet fixed ? :o

**Comment by franc6** [comment] 2020-01-23 20:53
I'm running into what might be a similar problem.

It seems if the TZID is known to the system, that it's parsed correctly, but if it's not know, then it fails, even though the TZID is defined.

For example, this one succeeds:

```
BEGIN:VCALENDAR
PRODID:Tom
VERSION:2.0
BEGIN:VEVENT
SUMMARY:Jobba
DTSTART;TZID=Europe/Berlin:20200121T070000
DTEND;TZID=Europe/Berlin:20200121T153000
UID:040000008200E00074C5B7101A82E00800000000B01768504EA0D5010000000000000000100000001A9B2363ACC29B4A85D65E582DC139B7
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191230T164515Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

This one fails:
```
BEGIN:VCALENDAR
PRODID:Tom
VERSION:2.0
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:MESZ
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:MEZ
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Jobba
DTSTART;TZID=W. Europe Standard Time:20200121T070000
DTEND;TZID=W. Europe Standard Time:20200121T153000
UID:040000008200E00074C5B7101A82E00800000000B01768504EA0D5010000000000000000100000001A9B2363ACC29B4A85D65E582DC139B7
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191230T164515Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

Finally, if I change the TZID to "Europe/Berlin" and modify the VTIMEZONE to indicate that it's +0800 instead of +0100, the times are still parsed with the proper time zone information for Europe/Berlin.  Like so:

```
BEGIN:VCALENDAR
PRODID:Tom
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0800
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:MESZ
TZOFFSETTO:+0900
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0900
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:MEZ
TZOFFSETTO:+0800
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Jobba
DTSTART;TZID=Europe/Berlin:20200121T070000
DTEND;TZID=Europe/Berlin:20200121T153000
UID:040000008200E00074C5B7101A82E00800000000B01768504EA0D5010000000000000000100000001A9B2363ACC29B4A85D65E582DC139B7
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191230T164515Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

Here's my sample code:
```
from ics import Calendar, Event
c = Calendar(open("calendar.ics").read().replace('\0', ''))
for e in c.events:
    print("{}\n\tstart: {}\n\tend: {}\n".format(e.name, e.begin, e.end))
```

**Comment by N-Coder** [comment] 2020-06-21 12:34
We should now have a test case that checks this and prevents regressions:
https://github.com/C4ptainCrunch/ics.py/blob/01172505f3eebc792a6a3445a00f2ef0aed9b80d/tests/issues/gh181_188.py
This test passed with the latest version of the `timezones` branch, so this issue should be solved (it will be closed once we merge the branch):
https://github.com/C4ptainCrunch/ics.py/runs/792496212

**Comment by praichor** [comment] 2020-07-28 09:05
I had the same problem, and found out the following:
It seems that the  `_populate` function of the `Component` class iterates over all `line_name` in a nondeterministic order, because  `self.Meta.parser.get_parsers()` returns a dictionary. This makes it possible that the events are parsed before the timezone definitions are parsed.

A workaround is the following:
Instead of just doing
```
calendar = ics.Calendar(text)
```
you can do:
```
timezonescalendar = ics.Calendar(text)
calendar = ics.Calendar()
# First populate the timezones:
calendar._timezones = timezonescalendar._timezones
# Then parse the events using the timezones.
containers = ics.icalendar.calendar_string_to_containers(text)
assert len(containers) == 1
calendar._populate(containers[0])
```

Of course, the better solution is to fix that problem in the ics library itself.

**Comment by N-Coder** [comment] 2020-07-28 09:48
Jep, that's one of the many issues with v0.7, which are [fixed](https://github.com/C4ptainCrunch/ics.py/blob/3b544fba4b46430fc624e425bf6ddc9ea1cd9406/src/ics/converter/calendar.py#L41) in v0.8. Unfortunately, there are some other not so easy to circumvent problems with timezones in v0.7 (e.g. vTimezones can't be generated by the library, python timezones are not serializeable and their IDs/names are a mess). As all of that should be fixed with v0.8, I'm now thinking about doing an alpha release of that version soonish, so that you get to use/test all those new features and help me find any remaining bugs. :smile:

**Comment by praichor** [comment] 2020-07-28 10:18
> Jep, that's one of the many issues with v0.7, which are [fixed](https://github.com/C4ptainCrunch/ics.py/blob/3b544fba4b46430fc624e425bf6ddc9ea1cd9406/src/ics/converter/calendar.py#L41) in v0.8. Unfortunately, there are some other not so easy to circumvent problems with timezones in v0.7 (e.g. vTimezones can't be generated by the library, python timezones are not serializeable and their IDs/names are a mess). As all of that should be fixed with v0.8, I'm now thinking about doing an alpha release of that version soonish, so that you get to use/test all those new features and help me find any remaining bugs. 😄

Sounds very good to me. Thanks!

**Comment by 0187773933** [comment] 2020-08-21 04:51
I think the arrow module reads the date as UTC timezone by default.
You have to manually set the timezone, and then it sets the right times.

```
from ics import Calendar, Event
import arrow

c = Calendar()
e = Event()
e.begin = arrow.get( "2020-09-06 00:00:01" , "YYYY-MM-DD HH:mm:ss" ).replace( tzinfo="US/Eastern" )
e.end = arrow.get( "2020-09-06 23:59:59" , "YYYY-MM-DD HH:mm:ss" ).replace( tzinfo="US/Eastern" )
e.name = "Test Event"
e.description = "Test Description"
c.events.add( e )
```

**Comment by praichor** [comment] 2020-08-21 06:18
> I think the arrow module reads the date as UTC timezone by default.
> You have to manually set the timezone, and then it sets the right times.

I'm not sure what you want to say, because this issue is about parsing ics files, not about creating events in Python.

**Closed** 2021-08-18 13:31 UTC
Labels: bug
